Group a keo
CodeSpace-Academy/ASE_2023_GROUP_A pull request #61
Opened 2023-10-10 15:11 UTC by K-Magano

Created Instructions component and completed #8

2023-10-11 10:50 UTC, Renzo-codespace commented on helpers/mongoDB-utils.js
Best practice would be get the entire connection string from the .env file. 
Having it partly hardcoded like this means this program can only connect to that db, but if it comes entirely from the .env,  the db it connects can be easily changed.

End each try block where you use the client with finally {client.close()}

2023-10-11 10:53 UTC, Renzo-codespace commented on next.config.js
Usernames, passwords and other database details should NEVER be committed.

2023-10-11 11:21 UTC, Cbazil submitted a review, later dismissed

2023-10-11 12:49 UTC, Renzo-codespace requested changes
Please remove the all sensitive data from the code base.

2023-10-12 10:52 UTC, Renzo-codespace submitted a review, later dismissed
Issues I raised earlier can be addressed when we start implementing best practices.

2023-10-13 06:54 UTC, Renzo-codespace approved these changes
Code shouldn't be commented out, rather deleted.

2023-10-13 07:33 UTC, Cbazil approved these changes

2023-10-13 07:33 UTC, merged