Ase#11 lulu mosobe update description
CodeSpace-Academy/ASE_2023_GROUP_A pull request #88
Opened 2023-10-19 09:41 UTC by MOSOBELULU

2023-10-19 09:43 UTC, Mpho-vincent-makgwe approved these changes

2023-10-19 09:51 UTC, Cbazil requested changes
The landing page card doesn't update and the individual recipe updates but doesn't persist. Please make sure it points to the same collection.

2023-10-20 13:07 UTC, Cbazil submitted a review, later dismissed

2023-10-20 13:09 UTC, OratileMokgoatlheng submitted a review, later dismissed

2023-10-20 16:14 UTC, Cbazil approved these changes

2023-10-21 13:16 UTC, Mpho-vincent-makgwe approved these changes

2023-10-21 16:13 UTC, shaniquah approved these changes

2023-10-23 06:56 UTC, Cbazil approved these changes

2023-10-23 07:06 UTC, closed without merging